# Server Port Configuration
server:
  port: 8080
spring:
  application:
    name: server
  # Config Server Configuration if any
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# Actuator Configuraiton
management:
  # Web Endpoint
  endpoints:
    web:
      exposure:
        include:
          - "*"
  # Shutdown Endpoint
  endpoint:
    shutdown:
      access: unrestricted
  # Info Endpoint
  info:
    env:
      enabled: true
# Info ENV Config
info:
  app:
    # Any set of property & value can be given
    name: server
    description: A Sample Server description
    version: 2.9.3
# Eureka Client Config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka

# Not needed (Appn specifc required for an API)
appinfo:
  build:
    version: s1:2.3

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 80
    # resilience4j.circuitbreaker:
    instances:
      route-circuitbreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50