# Server Port Configuration
server:
  port: 8070
spring:
  application:
    name: eurekaserver
  # Config Client Configuration if any goes here

# Actuator Configuration
management:
  # Web Endpoints
  endpoints:
    web:
      exposure:
        include:
          - "*"
  # Enabling Health Probe
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    # Based on the above after missing three heartbeat, the service will be evicted
    lease-expiration-duration-in-seconds: 30
  server:
    eviction-interval-timer-in-ms: 60000 # Scheduler running every min
    renewal-percent-threshold: 0.65
    renewal-threshold-update-interval-ms: 65000 # Check & Update threshold value every 1 min 5 sec
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
