server:
  port: 9000
spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5000
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    gateway:
      access: unrestricted
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: gatewayserver
    description: Edge Server for the entire microservice network
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 80
    instances:
      server-circuitbreaker:
        base-config: default
        failure-rate-threshold: 50
