server:
  port: 9080
spring:
  application:
    name: cloudfunc
  profiles:
    active:
      - default
  config:
    import:
      - "optional:configserver:http://localhost:8090/"
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
